name: Publish üêç distributions üì¶ to PyPI

on:
  push:
    branches:
      - automate-test
jobs:
  build-and-publish:
    name: Build and publish üêç distributions üì¶ to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
          python3 -m pip install setuptools wheel twine
      # version gets minor bump for master push
#      - name: Bump package build version
#        uses: michmich112/version-bumper@master
#        with:
#          scheme: semantic
#          version-file: "./setup.py"
#          files: "[]"
#          rules: '[{"trigger":"commit","branch":"master","bump":"build"}]'
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build a binary wheel and a source tarball
#        run: |
#          pipenv run build
#      # git tag without branch suffix is created for master
#      - name: Bump git tag version
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v5.6
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Create a GitHub release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}
#
#      - name: Github upload
#        uses: fnkr/github-action-ghr@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        env:
#          GHR_PATH: dist/
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution üì¶ to Test PyPI
        run: |
          pipenv run build
          pipenv run deploy --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          TWINE_REPOSITORY: testpypi


#      - name: Publish distribution üì¶ to PyPI
#        run: |
#          pipenv run build
#          pipenv run deploy
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}