name: Publish miriam

on:
  push:
    branches:
      - ga_test
jobs:
  build-and-publish:
    name: Build and publish üêç distributions üì¶ to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
#      - name: Build a binary wheel and a source tarball
#        run: |
#          pipenv run build
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: setup.py
          tagFormat: version=${version},
        id: version_check_staging
          - name:
            run: |
            echo "Version ${{steps.version_check_staging.outputs.releaseVersion}}"
#        git tag without branch suffix is created for master
#      - name: Bump git tag version
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v5.6
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Create a GitHub release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}

#
#      - name: Publish distribution üì¶ to PyPI
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}